version: "3"


services:
  app:
    working_dir: /app
    container_name: app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./controle-financeiro-app:/app/
    ports:
      - "9000"
    depends_on:
      - db
    networks:
      - rabbitmq_go_net

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=laravel
    ports:
      - "55432:5432"
    volumes: #      - docker/db/create.sql:/docker-entrypoint-initdb.d/create.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - rabbitmq_go_net

  web:
    image: nginx:1.17-alpine
    container_name: web
    ports:
      - "8055:80"
    environment:
      - CONTAINER_PHP=app
    volumes:
      - ./controle-financeiro-app:/app
      - ./.docker/web/nginx.default:/etc/nginx/conf.d/default.conf
    networks:
      - rabbitmq_go_net
    depends_on:
      - app
#
#  redis:
#    image: redis:7.0.0
#    container_name: cache
#    ports:
#      - "6379:6379"
#    volumes:
#      - cache:/data
#    networks:
#      - rabbitmq_go_net
#
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitdata:/var/lib/rabbitmq/
#    networks:
#      - rabbitmq_go_net
#  consumer:
#    image: consumer:v4
#    container_name: consumer
#    environment:
#      - QUEUE=queue.service4
#    networks:
#      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
volumes:
  rabbitdata:
  db-data:
    driver: local
  cache:
    driver: local
